services:
  web:
    build: ./bot_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bot_service:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  connector:
    build: ./connector_service
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - web

volumes:
  postgres_data: